# Generated by Django 2.1 on 2018-09-17 23:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_by', models.CharField(max_length=200)),
                ('sumber', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('edit_date', models.DateField()),
            ],
        ),
    ]
