# Generated by Django 2.1 on 2018-09-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('created_by', models.CharField(max_length=200)),
                ('sumber', models.CharField(max_length=200)),
                ('edit_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artikel_app.Artikel')),
            ],
        ),
    ]
