# Generated by Django 2.1 on 2018-09-17 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artikel_app.Artikel')),
            ],
        ),
    ]
