# Generated by Django 2.1 on 2018-09-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_app', '0002_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='artikel',
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
