# Generated by Django 2.1 on 2018-09-17 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_app', '0002_artikel_isi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='isi',
        ),
    ]
