# Generated by Django 2.1 on 2018-09-17 00:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_app', '0003_remove_artikel_isi'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='isi',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
