# Generated by Django 2.1 on 2018-09-18 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_app', '0004_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='artikel',
        ),
        migrations.AddField(
            model_name='artikel',
            name='kategori',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='artikel_app.Kategori'),
            preserve_default=False,
        ),
    ]
