# Generated by Django 2.1 on 2018-09-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_app', '0005_auto_20180918_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='kategori',
        ),
        migrations.AddField(
            model_name='artikel',
            name='kategori',
            field=models.ManyToManyField(to='artikel_app.Kategori'),
        ),
    ]
