# Generated by Django 2.1 on 2018-09-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_app', '0006_auto_20180918_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='sumber_url',
            field=models.CharField(default=1, max_length=800),
            preserve_default=False,
        ),
    ]
