# Generated by Django 2.1 on 2018-09-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_app', '0007_artikel_sumber_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='sumber_url',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
