# Generated by Django 2.1 on 2018-09-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_app', '0008_auto_20180920_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'ordering': ['-edit_date']},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'ordering': ['nama']},
        ),
    ]
