# Generated by Django 2.1 on 2018-09-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel_app', '0009_auto_20180922_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='foto_sampul',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
