# Generated by Django 2.1 on 2018-09-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kota',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Kota'},
        ),
    ]
