# Generated by Django 2.1 on 2018-09-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jadwal',
            new_name='Schedule',
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-tanggal']},
        ),
    ]
