# Generated by Django 2.1 on 2018-09-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-pub_date',)},
        ),
    ]
