# Generated by Django 2.1 on 2018-09-06 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keperluan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='kategori',
            name='Keperluan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.Keperluan'),
        ),
        migrations.AddField(
            model_name='expense',
            name='Keperluan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.Keperluan'),
        ),
        migrations.AddField(
            model_name='expense',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.Kategori'),
        ),
    ]
