# Generated by Django 2.1 on 2018-09-06 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keperluan',
            new_name='Anggaran',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='Keperluan',
            new_name='anggaran',
        ),
        migrations.RenameField(
            model_name='kategori',
            old_name='Keperluan',
            new_name='anggaran',
        ),
    ]
