# Generated by Django 2.1 on 2018-09-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_auto_20180906_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('anggaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.Anggaran')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_app.Kategori')),
            ],
        ),
        migrations.RemoveField(
            model_name='expense',
            name='anggaran',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='kategori',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
